name: Discord Rich Presence Activity Badge
on:
  schedule:

    - cron: "30 0-23 * * *" # Customizable 15 Minutes Less Not Allowed!, At minute 30 past every hour from 0 through 23.

  workflow_dispatch:

jobs:
  BadgeUpdater:
    name: Discord Activity Watcher
    runs-on: ubuntu-latest

    steps:

      - name: Step 1 | Repository Checkout
      - uses: actions/checkout@master

      - name: Step 2 | Update README Discord Badge to Latest Upstream
      - uses: CodexLink/discord-rich-presence-activity-badge@main

        with:
          # These are required inputs.
          # More information on README - Parameters Section.
          WORKFLOW_INSTANCE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISCORD_USERNAME: ${{ secrets.DISCORD_USERNAME }}
          DISCORD_USERNAME_TAG: ${{ secrets.DISCORD_USERNAME_TAG }}
          OVERRIDE_COMMIT_MESSAGE: 'Discord Activity Reading Finished.'